app:
  name: "Task Manager"
  max-tasks: 5
  default-priority: "LOW"

spring:
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/META-INF/resources/webjars/
  mvc:
    static-path-pattern: /**
  profiles:
    active: dev

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - url: /v3/api-docs
        name: Task Manager API
    use-root-path: true
    disable-swagger-default-url: true

server:
  port: 8081

logging:
  level:
    org.springdoc: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot: DEBUG
    com.vasilevyuv: DEBUG